/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.view;

import com.controller.ambilCustomercomboItem;
import com.koneksi.koneksi;
import static com.koneksi.koneksi.*;
import com.model.model_inventory;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harits F
 */
public class TambahOrder extends javax.swing.JFrame {
    public static String CatId, CatName, id_products, all_products, stok_barang, id_customer;
    public static String nama_barang_harga, harga_ambil, TotalHarga, kolomHarga, jb;
    public static int barisCell = 0, harga_barang, jumlah_barang;
    public static String auto_num, auto_num_header;
    /**
     * Creates new form TambahOrder
     */
    public TambahOrder() {
        initComponents();
        Produk();
        BindCombo();
    }
    public void BindCombo(){
        ambilCustomercomboItem mq = new ambilCustomercomboItem();
        HashMap<String, Integer> map = mq.populateCombo();
        for(String s : map.keySet()){
            j_customer.addItem(s);
        }
    }
    
    public void Produk(){
        try{
            j_produk.removeAllItems();
            j_produk.addItem("");
            conn = koneksi.koneksi();
            String bacaSemuaData = "SELECT kd_barang, nama_barang, harga, stok_barang FROM barang";
            pst = conn.prepareStatement(bacaSemuaData);
            res = pst.executeQuery();
            while(res.next()){
                all_products = res.getString(2);
                stok_barang = res.getString(4);
                j_produk.addItem(all_products);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void autonumberDetailOrder(){
        try{
            String an = "SELECT MAX(no_order) FROM detail_order";
            pst = conn.prepareStatement(an);
            res = pst.executeQuery();
            if (res.next()){
                int a = res.getInt(1);
                auto_num=(Integer.toString(a+1));
            }
            res.close();
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void autonumberOrder(){
        try{
            String an = "SELECT MAX(no_order) FROM header_order";
            pst = conn.prepareStatement(an);
            res = pst.executeQuery();
            if (res.next()){
                int a = res.getInt(1);
                auto_num_header=(Integer.toString(a+1));
            }
            res.close();
            pst.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_produk = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        j_customer = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        t_order = new javax.swing.JButton();
        h_order = new javax.swing.JButton();
        order_barang = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataOrder = new javax.swing.JTable();

        j_produk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        j_produk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                j_produkItemStateChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer");

        j_customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("(+) Customer");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        t_order.setText("( + ) Barang");
        t_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_orderActionPerformed(evt);
            }
        });

        h_order.setText("( - ) Barang");
        h_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h_orderActionPerformed(evt);
            }
        });

        order_barang.setText("Order Barang");
        order_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_barangActionPerformed(evt);
            }
        });

        dataOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Produk", "Harga", "Kuantitas", "Total Harga"
            }
        ));
        dataOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dataOrderKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(dataOrder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(j_customer, 0, 142, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(320, 320, 320))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(t_order)
                        .addGap(37, 37, 37)
                        .addComponent(h_order)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(order_barang)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(j_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_order)
                    .addComponent(h_order))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(order_barang)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void h_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h_orderActionPerformed
            // TODO add your handling code here:
        if(dataOrder.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(h_order, "Pilih datanya pada tabel dibawah ini!!!");
            }else{
                DefaultTableModel model = (DefaultTableModel)dataOrder.getModel();
                model.removeRow(dataOrder.getSelectedRow());
            }
           int getRow=dataOrder.getRowCount();
           dataOrder.changeSelection(getRow-1, 0, false, false);
    }//GEN-LAST:event_h_orderActionPerformed

    private void order_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_barangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_order_barangActionPerformed

    private void j_produkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_j_produkItemStateChanged
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)dataOrder.getModel();
        barisCell = dataOrder.getSelectedRow();
        try{
            //cara agar diset 0 setelah klik combobox
            dataOrder.setValueAt(null, barisCell, 3);
            dataOrder.setValueAt(null, barisCell, 4);
            
            conn = koneksi.koneksi();
            nama_barang_harga = j_produk.getSelectedItem().toString();  
            String bacaSemuaData = "SELECT kd_barang, harga FROM barang where nama_barang='"+nama_barang_harga+"'";
            pst = conn.prepareStatement(bacaSemuaData);
            res = pst.executeQuery();
            while(res.next()){
                id_products = res.getString(1);
                harga_ambil = res.getString(2);
                model.setValueAt(id_products, barisCell, 0);
                model.setValueAt(harga_ambil, barisCell, 2);
                //t_harga.setText(value);
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_j_produkItemStateChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new TambahCustomer().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void dataOrderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dataOrderKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)dataOrder.getModel();
        barisCell = dataOrder.getSelectedRow();
        jumlah_barang=0;
        try{
            kolomHarga = (String) dataOrder.getValueAt(barisCell, 2);
            jb = (String) dataOrder.getValueAt(barisCell, 3);

            jumlah_barang = Integer.parseInt(jb);
            Integer intObject = new Integer(kolomHarga);
            harga_barang = intObject.intValue()* jumlah_barang;
            TotalHarga = String.valueOf(harga_barang);

            model.setValueAt(TotalHarga, barisCell, 4);
        }catch(Exception e){
        }
    }//GEN-LAST:event_dataOrderKeyReleased

    private void t_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_orderActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)dataOrder.getModel();
        model.addRow(new Object[]{""});
    }//GEN-LAST:event_t_orderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable dataOrder;
    private javax.swing.JButton h_order;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> j_customer;
    private javax.swing.JComboBox<String> j_produk;
    private javax.swing.JButton order_barang;
    private javax.swing.JButton t_order;
    // End of variables declaration//GEN-END:variables
}
